# Generated by Django 5.2.1 on 2025-06-19 19:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="commenttype",
            name="code",
            field=models.CharField(
                choices=[
                    ("SC", "Scientific Comment"),
                    ("rSC", "Response to Scientific Comment"),
                    ("ER", "Error Correction"),
                    ("AD", "Additional Data"),
                    ("NP", "New Publication"),
                ],
                max_length=10,
                unique=True,
            ),
        ),
        # CommentChat und ChatMessage werden NICHT nochmal erstellt,
        # da sie bereits in 0001_initial.py existieren
    ]