# Generated by Django 5.2.1 on 2025-05-22 00:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        # This migration previously altered Author and Comment models
        # which have been removed from core app to avoid duplication
        # with the comments and publications apps
    ]
