# Generated by Django 5.2.1 on 2025-05-26 09:04

from django.db import migrations


def create_default_groups(apps, schema_editor):
    # Create default groups
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="readers")
    Group.objects.get_or_create(name="authors")
    Group.objects.get_or_create(name="moderators")


def delete_default_groups(apps, schema_editor):
    # Delete default groups
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name__in=["readers", "authors", "moderators"]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_alter_author_user_alter_comment_status_user"),
    ]

    operations = [
        migrations.RunPython(create_default_groups, delete_default_groups),
    ]
