# Generated by Django 5.0 on 2025-06-11 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_create_default_groups"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publication",
            name="meta_doi",
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
