# Generated by Django 5.0 on 2025-06-11 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_create_default_groups"),
    ]

    operations = [
        # This migration previously altered the Publication model
        # which has been removed from core app to avoid duplication
        # with the publications app
    ]
