# Generated by Django 5.2.1 on 2025-06-01 10:00

from django.db import migrations


def create_commentators_group(apps, schema_editor):
    # Create commentators group
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="commentators")


def delete_commentators_group(apps, schema_editor):
    # Delete commentators group
    Group = apps.get_model("auth", "Group")
    Group.objects.filter(name="commentators").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_publication_meta_doi"),
    ]

    operations = [
        migrations.RunPython(create_commentators_group, delete_commentators_group),
    ]