# Generated by Django 5.2.1 on 2025-05-22 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversion",
            name="reviewer_response",
            field=models.TextField(
                blank=True,
                help_text="Response to reviewer/editor recommendations for revised submissions",
                null=True,
            ),
        ),
    ]
