# Generated by Django 5.2.1 on 2025-05-23 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publications', '0002_documentversion_reviewer_response'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='meta_doi',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]