# Generated by Django 5.0 on 2025-06-13 11:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0003_alter_publication_meta_doi"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversion",
            name="original_file",
            field=models.CharField(
                blank=True,
                help_text="Path to the original imported file",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="author_contributions",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="conclusion",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="introduction",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="main_text",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="methodology",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="references",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documentversion",
            name="technical_abstract",
            field=models.TextField(blank=True, null=True),
        ),
    ]
