# Generated by Django 5.0 on 2025-06-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0004_documentversion_original_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="documentversion",
            name="html_content",
            field=models.TextField(
                blank=True,
                help_text="HTML version of the content for display",
                null=True,
            ),
        ),
    ]
