# Generated by Django 5.0 on 2025-06-17 15:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("publications", "0007_alter_documentversion_discussion_closed_by_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="documentversion",
            name="html_content",
        ),
    ]
